### ISSUE TITLE
[FEATURE REQUEST] Dataset submission guide

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#169]
**Is your feature request related to a problem? Please describe.**
Add a dataset submission guid in CONTRIBUTING.md to standardize the submission workflow.

**Describe the solution you'd like**
Need a systematic step-by-step instruction on how to construct and contribute a dataset. Some random steps coming up my mind:

- Construction of metadata.json and task.json
- README writing guide (#98)
- Request the implementation of a new task type if none of existing ones fit the new dataset

**Comment by StevenGolden1203** [comment]
@jiaqima  After we settle down on the submission guide, I can add an auto comment bot for first time contributors, leading them to read the guide

**Comment by jiaqima** [comment]
> @jiaqima After we settle down on the submission guide, I can add an auto comment bot for first time contributors, leading them to read the guide

Sounds good. I'll work on the submission guide this weekend.
