### ISSUE TITLE
[FEATURE REQUEST] CONTRIBUTING.md missing GraphRegression

### ISSUE THREAD

**Issue by JasonHezhengFan** [Graph-Learning-Benchmarks/gli#196]
**Is your feature request related to a problem? Please describe.**

CONTRIBUTING.md missing GraphRegression, which is already in ogbg-molfreesolv

**Comment by jiaqima** [comment]
The list of tasks now moved to FORMAT.md.

**Comment by jiaqima** [comment]
Closed by #386
