### ISSUE TITLE
Remove `examples/`

### ISSUE THREAD

**Issue by xingjian-zhang** [Graph-Learning-Benchmarks/gli#251]
**Is your feature request related to a problem? Please describe.**
The `examples/` dir should be deprecated.

**Describe the solution you'd like**
Remove the dir completely.

**Comment by xingjian-zhang** [comment]
@jiaqima What do you think?

**Comment by jiaqima** [comment]
I'm not sure if we should keep the two with npz files?

**Comment by xingjian-zhang** [comment]
Sure, we can keep them. I am not sure of the reasons, tho. Perhaps for the contributors' reference?

**Comment by jiaqima** [comment]
> Sure, we can keep them. I am not sure of the reasons, tho. Perhaps for the contributors' reference?

Yeah, I think it's helpful for the developers. Also can be used to demonstrate the difference between read_glb_graph and get_glb_graph. And how to test datasets not installed in the glb package yet.
