### ISSUE TITLE
[FEATURE REQUEST] Update `codecheck.sh` to support pytest locally

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#256]
**Is your feature request related to a problem? Please describe.**
[GitHub-supported runners only have 7 GB RAM and 14 GB SSD](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). We therefore cannot run pytest through GitHub actions for large datasets. 

**Describe the solution you'd like**
A possible solution to this problem is for large dataset contributors to run pytest locally on their own machine and then upload the pytest results together with the PR. To ease this step, we should update `codecheck.sh` (or create a new script like this) to include pytest. Ideally, this script should mimic the current pytest workflow and create a result file when the dataset contributor run it locally. The contributor will then upload the pytest result file online and attach the link to it in the PR. 

Perhaps we can also open a public Google Group so the dataset contributors can email the pytest result files to the group.

**Additional context**

GitHub-supported runners:

![](https://user-images.githubusercontent.com/5397179/187108895-10bc9837-3c25-40da-a98b-4be39a937227.png)

**Comment by jiaqima** [comment]
I think we can ask the contributor to copy and paste the local pytest outputs to the PR when the dataset is too large for Github Action. The contributor should also add the dataset to the list of large datasets in the yaml file to be implemented in #257. 

Finally, we can implement a Github Action that automatically comments on a PR to ask for local pytest outputs, if it finds a PR makes change to any dataset listed in the list of large datasets.

**Comment by StevenGolden1203** [comment]
> I think we can ask the contributor to copy and paste the local pytest outputs to the PR when the dataset is too large for Github Action. The contributor should also add the dataset to the list of large datasets in the yaml file to be implemented in #257.
> 
> Finally, we can implement a Github Action that automatically comments on a PR to ask for local pytest outputs, if it finds a PR makes change to any dataset listed in the list of large datasets.

I will try to add this function in `pytest.yml`.

**Comment by jiaqima** [comment]
The main purpose of this issue, updating `codecheck.sh`, has been fully achieved after PR #319. Closing this issue in favor of #331, which is dedicated to the follow-up discussion above.
