### ISSUE TITLE
[FEATURE REQUEST] Use a separate file to maintain the list of large datasets

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#257]
**Is your feature request related to a problem? Please describe.**
Currently the list of large datasets that cannot be tested by GitHub actions is hard-coded in the test code. 

https://github.com/Graph-Learning-Benchmarks/gli/blob/bae59ebb4b135b47925bd5109309655e8cefb30f/tests/test_data_loading.py#L20

**Describe the solution you'd like**
Use a separate yaml file (e.g., name it as `/tests/config.yaml`) to store such special accommodations.

**Additional context**
See also #256

**Comment by jiaqima** [comment]
Hi @StevenGolden1203, could you help on this issue?

**Comment by StevenGolden1203** [comment]
Ok! I will work on this.
