### ISSUE TITLE
[BUG] to_dense works for heterograph, which should raise error

### ISSUE THREAD

**Issue by StevenGolden1203** [Graph-Learning-Benchmarks/gli#267]
`to_dense` in gli/utils works for hetergraph, which is not the expected behavior.

**To Reproduce**
```
import gli
from dgl.dataloading import GraphDataLoader
from gli.utils import to_dense

data = gli.dataloading.get_gli_dataset("ogbg-molhiv", "task")
train_data = data[0]
train_loader = GraphDataLoader(train_data, batch_size=128)
for batch, (batched_graph, labels) in enumerate(train_loader):
    print(type(batched_graph))
    to_dense(batched_graph)
    break
```

output:
```
<class 'dgl.heterograph.DGLHeteroGraph'>
```

**Expected behavior**

An error should be raised, b/c: https://github.com/Graph-Learning-Benchmarks/gli/blob/main/gli/utils.py#L489

**Screenshots**
![image](https://user-images.githubusercontent.com/84695981/188050844-1fcb8edf-ff3a-4da3-8195-7ac6faa59461.png)

**Comment by xingjian-zhang** [comment]
This is because all dgl graphs are `dgl.heterograph.DGLHeteroGraph`. For example,
```python
import dgl
type(dgl.rand_graph(5, 5))
```
Output:
```
dgl.heterograph.DGLHeteroGraph
```


To determine if the graph is homogeneous or not:
```python
batched_graph.is_homogeneous
```
output
```
True
```
Therefore, the `batched_graph` is essentially a homograph, which should be fine.
