### ISSUE TITLE
[BUG] Pytest fails when deleting a dataset in PR

### ISSUE THREAD

**Issue by StevenGolden1203** [Graph-Learning-Benchmarks/gli#278]
As titled.

**Comment by xingjian-zhang** [comment]
Can you give more error messages?

**Comment by StevenGolden1203** [comment]
@xingjian-zhang Sorry that I missed your comment! When deleting a dataset, for example, Cora. workflow will notice that Cora is changed, so it will try to run pytest on Cora. This will lead to error b/c Cora is already deleted. The test must fail in such cases.

I am working on this bug right now. But I think it will not block our current workflow.
