### ISSUE TITLE
Data uploading link is deprecated

### ISSUE THREAD

**Issue by xingjian-zhang** [Graph-Learning-Benchmarks/gli#293]
**Describe the bug**
- The current data uploading link in https://github.com/Graph-Learning-Benchmarks/gli/blob/main/CONTRIBUTING.md#uploading-gli-data-files is deprecated.
- The anonymous repo might contain this link.

**Expected behavior**
Not sure if we should update the new link. @jiaqima

**Comment by jiaqima** [comment]
Let's remove the link for now and add it later. The Google Drive link is too slow for large files. We may need to find an alternative solution.

**Comment by jiaqima** [comment]
Temporarily fixed by #301. Opened a new PR #302 for a better long-term solution.
