### ISSUE TITLE
[BUG] Change all npz files into the new format and add LICENSE files

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#327]
Following the changes made in PR #325, the npz files and urls.json of all the datasets need to be updated. We want to migrate the urls from Google Drive to the new file storage solution discussed in #302 at the same time.

**Comment by xingjian-zhang** [comment]
# TODO

I added a TODO list here for us to check the progress:

- [ ] FB13
- [ ] FB15K
- [ ] FB15K237
- [ ] NELL-995
- [ ] WN11
- [ ] WN18
- [ ] WN18RR
- [ ] YAGO3-10
- [ ] actor
- [ ] arxiv-year
- [ ] chameleon
- [ ] cifar
- [ ] citeseer
- [ ] cora
- [ ] cornell
- [ ] genius
- [ ] mnist
- [ ] ogbg-molbace
- [ ] ogbg-molclintox
- [ ] ogbg-molfreesolv
- [ ] ogbg-molhiv
- [ ] ogbg-molmuv
- [ ] ogbg-molpcba
- [ ] ogbg-molsider
- [ ] ogbl-collab
- [ ] ogbn-arxiv
- [ ] ogbn-mag
- [ ] ogbn-products
- [ ] ogbn-proteins
- [ ] penn94
- [ ] pokec
- [ ] pubmed
- [ ] snap-patents
- [ ] squirrel
- [ ] texas
- [ ] twitch-gamers
- [ ] wiki
- [ ] wisconsin

**Comment by jiaqima** [comment]
Here is a reminder that we can add the LICENSE at the same time.

**Comment by jiaqima** [comment]
@xingjian-zhang, @jupiterepoch, @StevenGolden1203 

I've completed my part for both the npz files (#367) and the LICENSE files (#371). Adding a LICENSE to a dataset turns to be a bit complicated. 

For now, let's try to do the following for adding LICENSE (more details can be found in the comments of PR #371):

1. Update `README.md`

1.1) For each version of the dataset listed in README.md, add a website link to the dataset. 

1.2) For each version of the dataset listed in README.md, add a license link to the dataset. If there is no license found for that version of dataset, mark it as "LICENSE: missing".

See [pubmed README](https://github.com/Graph-Learning-Benchmarks/gli/tree/main/datasets/pubmed) as an example: 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/5397179/198897398-7d7b4f4a-a876-4de6-b6fd-b3c551bd149a.png">

2. Add a `LICENSE` file. If the "Current Version" source has a license, copy that license to the `LICENSE` file. Otherwise, add an empty `LICENSE` file (even if the "Original Source" or a "Previous Version" has a license).

**Comment by jiaqima** [comment]
Fixed by a series of PRs.
