### ISSUE TITLE
[FEATURE REQUEST] A Github Action automatically commenting on PR modifying large datasets

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#331]
**Is your feature request related to a problem? Please describe.**
When a dataset is too large to fit in the 7 GB memory limit of pytest on Github Action, we need to ask the user to provide the test results of local `make test`.

**Describe the solution you'd like**
Have a Github Action workflow that automatically identifies PRs modifying large datasets and asks for test results.

The workflow may consist of the following steps:

1. Triggered by a new PR. 
2. Get the list of datasets modified by this PR.
3. Check if any modified datasets are listed in `large_dataset_to_skip ` in `tests/config.yaml`.
4. Send a comment to the PR saying the following

```
This is an automatic reminder for pasting the local test results of <list of datasets> as a comment in this PR, in case you haven't done so. 
The aforementioned datasets are too large for them to be tested with GitHub Action workflow here. 

The local test result for each dataset can be obtained by running `make pytest DATASET=<dataset name>`. 
For more details, please refer to [the dataset submission guide](https://github.com/Graph-Learning-Benchmarks/gli/blob/main/CONTRIBUTING.md#contributing-a-new-dataset).
```

**Additional context**
See this discussion: https://github.com/Graph-Learning-Benchmarks/gli/issues/256#issuecomment-1261494104

**Comment by StevenGolden1203** [comment]
Closing this issue since https://github.com/Graph-Learning-Benchmarks/gli/pull/361 is merged.
