### ISSUE TITLE
Cannot identify the type of some matrix in ogbn-* dataset[BUG]

### ISSUE THREAD

**Issue by GreatSnoopyMe** [Graph-Learning-Benchmarks/gli#364]
**Describe the bug**
Some of the variables in the ogbn-* dataset cannot be identified by the `sp.issparse(matrix)` and `isinstance(matrix, np.ndarry)`,
causing the data not stored in `save_data`.

**To Reproduce**
See the screenshots

**Expected behavior**
Store the data.

**Screenshots**
The `edge` variable is not identified and is therefore not stored. See the utils.py.
![image](https://user-images.githubusercontent.com/94805969/196553408-a8497dac-b413-4b87-a441-8cefdf219081.png)
![image](https://user-images.githubusercontent.com/94805969/196553525-4db8b351-1bf2-4d02-9b11-6159bf523af5.png)
In the `pytest test_data_loading.py`, the `edge` variable is none.
![image](https://user-images.githubusercontent.com/94805969/196553765-7c8adf1b-18d6-4125-8a2c-7175b5e846ad.png)

**Comment by xingjian-zhang** [comment]
Got it. I am working on it.

**Comment by xingjian-zhang** [comment]
Is this still an issue? I am closing this issue given that #365 has been merged. Please comment if you still find it problematic.

**Comment by GreatSnoopyMe** [comment]
When I generate the new npz file for `ogbn-arxiv` yestarday, there is some other issue with running `pytest`on it.
But this may not related to the `save_data()`, I will try to figure it out tonight.

**Comment by jiaqima** [comment]
Closing since it seems this is no longer a problem.
