### ISSUE TITLE
Get rid of `urls.json`

### ISSUE THREAD

**Issue by xingjian-zhang** [Graph-Learning-Benchmarks/gli#425]
**Is your feature request related to a problem? Please describe.**
Currently, we need `urls.json` throughout the life cycle of a newly-contributed dataset
- **when contributing**: contributors need to upload the npz files to DropBox and then copy&paste the download urls into a file `urls.json`.
- **during testing**: the data loading process will download the files in `urls.json`
- **after merging**: as planned, the data files will be transferred to AWS S3 storage, and the `urls.json` will be updated by GitHub Action when PR is merged.

**Describe the solution you'd like**
TL;DR - We should get rid of `urls.json` entirely, and replace it by a http service.
- **when contributing**: Contributors will need to call our `save_data` utility functions to pack a dataset locally, and the function will store the arrays into files with unique identifiers such as `cora_data_<hash>.npz` (and also save the file name into json files like `metadata.json`. Then, the contributors will upload the packed npz files to Dropbox (exactly the same step as before).
- **during testing**: the data loading process will make a http request to a service run on AWS EC2 (args: a list of filenames; return: a json map of filenames-to-urls). At this time, the npz files live in the DropBox.
- **after merging**: the data loading process will make a http request to a service run on AWS EC2 (args: a list of filenames; return: a json map of filenames-to-urls). At this time, the npz files live in AWS EC2.

**TODOs**
Here is a list of what functionality we need to implement:
- [x] #428
- [x] `gli.utils.download_data()` should download data not based on `urls.json`. Instead, the function should traverse all json files to find all the required npz files. Then, it should make a http call to the filename2url service and then download accordingly.
- [ ] http service `filename2url` on AWS EC2

**Comment by jiaqima** [comment]
> ... such as `cora_data_<hash>.npz` ...

I would recommend using separator such as double underscores `__` instead of a single underscore `_`, as the single underscore is very likely to be used by the contributor specified dataset name.

**Comment by jiaqima** [comment]
Two more relevant TODOs (although better open another issue to document them):

- Update dataloaders by downloading data from the http service
- Update the existing datasets (after implementing the `save_graph` and `save_task` functions)
  - Rename the npz files, update metadata.json and task json files, upload the new npz files
  - Remove urls.json
  - Update jupyter notebook

**Comment by xingjian-zhang** [comment]
> * Update dataloaders by downloading data from the http service

This one is the same with the second TODO I mentioned in this PR.
