### ISSUE TITLE
Tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by xingjian-zhang** [Graph-Learning-Benchmarks/gli#474]
**Describe the bug**
`gli.io` saves numpy int array with dtype of int32 by default. However, torch only supports int64 indexing for some versions.

**To Reproduce**
See #472 for reproduction.

**Expected behavior**
`gli.io` saves numpy int array with dtype of int64 by default.

**Additional context**
> Seems like when I use `gli.io.save_task_node_classification` to save `train_set`, `val_set` and `test_set` (int64 indices), it will first [convert them to list](https://github.com/Graph-Learning-Benchmarks/gli/blob/2302ac01fefeb421306d2d8891ad562102a6b5ac/gli/io/utils.py#L69) and then [to numpy array](https://github.com/Graph-Learning-Benchmarks/gli/blob/2302ac01fefeb421306d2d8891ad562102a6b5ac/gli/io/utils.py#L248).  The dtype numpy array will eventually become int32. (Instead, the default dtype should be int64)
> Hence, when loading indices from npz file in pytest `test_data_loading` of dtype int32, `mask[_indices]` fails with _Error tensors used as indices must be long, byte or bool tensors_.

> It works on my computer since my torch version == 2.1.1 while on server, torch version == 1.13.1

_Originally posted by @Jason-csc in https://github.com/Graph-Learning-Benchmarks/gli/issues/472#issuecomment-1832414794_

**Comment by Jason-csc** [comment]
The default dtype when [creating a numpy array](https://github.com/Graph-Learning-Benchmarks/gli/blob/2302ac01fefeb421306d2d8891ad562102a6b5ac/gli/io/utils.py#L248) varies across platform. On Mac and Linux, the default dtype is int64 while on 32bit/64bit windows, the default dtype is int32, which causes the error.
Windows is weried lol, but I think it would be better to set `dtype='int64'` when initialing numpy array.

**Comment by xingjian-zhang** [comment]
> The default dtype when [creating a numpy array](https://github.com/Graph-Learning-Benchmarks/gli/blob/2302ac01fefeb421306d2d8891ad562102a6b5ac/gli/io/utils.py#L248) varies across platform. On Mac and Linux, the default dtype is int64 while on either 32bit/64bit windows, the default dtype is int32, which causes the error. Windows is weried lol, but I think it would be better to set `dtype='int64'` when initialing numpy array for indices to be long type.

Yes, this is exactly what I implemented in #475. Thanks for the clarification！
